"""Metadata heuristics: titles, dates, and slugs from HTML and URLs.

Everything here is pure text processing. Each rule exists because a
real page needed it; tests/test_extraction.py pins one reproduction
per site.
"""

import calendar
import difflib
import html as html_lib
import re
import unicodedata
from urllib.parse import urlparse

MONTHS = {m.lower(): i for i, m in enumerate(calendar.month_name) if m} | {
    m.lower(): i for i, m in enumerate(calendar.month_abbr) if m
}


def published_date(url: str, html: str) -> str | None:
    """Publication date from the URL path or page metadata; None when unknown.

    Trust order: a date the author put in the URL, then machine-readable
    metadata (article:published_time meta, JSON-LD, <time>), then dates
    visible in the page text.
    """
    path = urlparse(url).path
    match = re.search(r"/(\d{4})/(\d{2})/(\d{2})(?:/|$)", path) or re.search(
        r"(\d{4})-(\d{2})-(\d{2})", path
    )
    if match:
        return "-".join(match.groups())
    for stamp in [
        meta_content(html, "article:published_time"),
        extract_first(html, r'"datePublished"\s*:\s*"([^"]+)"'),
        extract_first(html, r'<time[^>]*datetime=["\']([^"\']+)'),
    ]:
        if re.match(r"\d{4}-\d{2}-\d{2}", stamp):
            return stamp[:10]
    return body_date(html)


def extract_first(html: str, pattern: str) -> str:
    match = re.search(pattern, html)
    return match.group(1) if match else ""


def body_date(html: str) -> str | None:
    """First unambiguous date in the page body: ISO, named month, or M/D/YYYY.

    Slash dates are last and assume US month-first order; named months and
    ISO can't be misread. This whole tier is a heuristic destined to be
    replaced by an LLM fallback.
    """
    # Scan visible text only: drop comments (single-file stamps its own
    # save date into one) and then all markup, so dates inside href
    # attributes (links to OTHER dated posts, e.g. jaykmody.com linking
    # 2018-06-24-attention) can't win.
    text = re.sub(r"<!--.*?-->", "", html, flags=re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    if match := re.search(r"\b(20\d{2})-(\d{2})-(\d{2})\b", text):
        return "-".join(match.groups())
    for pattern, order in [
        # Ordinal suffixes included: "October 19th, 2011" (ridiculousfish)
        (r"\b([A-Za-z]{3,9})\.? (\d{1,2})(?:st|nd|rd|th)?,? (\d{4})\b", (2, 0, 1)),
        (r"\b(\d{1,2})(?:st|nd|rd|th)? ([A-Za-z]{3,9})\.? (\d{4})\b", (2, 1, 0)),
        (r"\b(\d{1,2})/(\d{1,2})/(\d{4})\b", (2, 0, 1)),
    ]:
        for match in re.finditer(pattern, text):
            year, month, day = (match.group(i + 1) for i in order)
            month = MONTHS.get(month.lower(), month if month.isdigit() else None)
            if month and 1 <= int(month) <= 12 and 1 <= int(day) <= 31:
                return f"{year}-{int(month):02d}-{int(day):02d}"
    return None


def meta_content(html: str, prop: str) -> str:
    """A meta tag's content: both attribute orders, both quote styles,
    and property= or name= (eev.ee writes <meta name="og:title">)."""
    for pattern in [
        rf'(?:property|name)=["\']{prop}["\'][^>]*content="([^"]+)"',
        rf"(?:property|name)=[\"']{prop}[\"'][^>]*content='([^']+)'",
        rf'content="([^"]+)"[^>]*(?:property|name)=["\']{prop}["\']',
        rf"content='([^']+)'[^>]*(?:property|name)=[\"']{prop}[\"']",
    ]:
        if match := re.search(pattern, html):
            text = html_lib.unescape(match.group(1))
            return re.sub(r"\s+", " ", text).strip()
    return ""


# Source priors: how much to trust each place a title can come from.
OG_SCORE = 3.0
CLASSED_HEADING_SCORE = 2.5
H1_SCORE = 1.5
TITLE_TAG_SCORE = 1.0
TITLE_REMAINDER_SCORE = 1.2  # <title> piece left after removing the h1
SLUG_BONUS = 1.0  # candidate matches the URL slug
LONGER_REMAINDER_BONUS = 0.5  # post titles run longer than section names
SITE_NAME_PENALTY = 5.0  # candidate is the site, not the post


def page_title(html: str, domain: str = "", url: str = "") -> str:
    """Best-scoring title candidate from og:title, headings, and <title>.

    Candidates are generated by markup-specific rules (which only add to
    the set, so they compose safely) and ranked by source priors plus a
    slug-affinity bonus and site-name penalties. Empty if none.
    """

    def clean(fragment: str) -> str:
        text = html_lib.unescape(re.sub(r"<[^>]+>", "", fragment))
        return re.sub(r"\s+", " ", text).strip()

    og = meta_content(html, "og:title")
    # The standard declaration of a site's display name, e.g. sites
    # that title pages "Post Title | Site Name" (dervis.de).
    og_site = meta_content(html, "og:site_name")
    headings = re.findall(r"<h([12])([^>]*)>(.*?)</h\1>", html, re.S)
    # A class-marked heading is the strongest heading signal: WordPress
    # puts a site-title h1 earlier in the DOM, and Obsidian Publish uses
    # an h2 (publish-article-heading) with no h1 at all.
    classed = next(
        (
            clean(body)
            for _, attrs, body in headings
            if re.search(r"(entry|post|article|page|publish)[-_](title|heading)", attrs)
        ),
        "",
    )
    h1 = next((clean(body) for level, _, body in headings if level == "1"), "")
    doc = re.search(r"<title[^>]*>([^<]+)</title>", html)
    doc = clean(doc.group(1)) if doc else ""
    # An h1 linking to the site root is a masthead; its text is the
    # site's display name, which may differ from the domain (eli.li's
    # masthead reads "« Oatmeal", and the site prefixes titles with it).
    masthead = next(
        (
            clean(body)
            for level, _, body in headings
            if level == "1"
            and re.search(r'href=["\'](?:/|https?://[^"\'/]+/?)["\']', body)
        ),
        "",
    )
    segments = [s for s in urlparse(url).path.split("/") if s]
    segment = slugify(segments[-1]) if segments else ""
    # Known ways the site refers to itself: masthead h1 text and the
    # declared og:site_name; the domain matches by containment.
    site_names = [name for name in (masthead, og_site) if name]

    def site_name(text: str) -> bool:
        return bool(text) and (
            compact(text) in compact(domain)
            or any(compact(text) == compact(name) for name in site_names)
        )

    scores: dict[str, float] = {}

    def add(text: str, score: float) -> None:
        # Some themes nest a date element inside the heading (mazzo.li).
        text = re.sub(r"^\d{4}-\d{2}-\d{2}\s+", "", text)
        for name in site_names:
            text = strip_site_name(text, name)
        text = strip_site_suffix(text, domain)
        if not text:
            return
        if site_name(text):
            score -= SITE_NAME_PENALTY
        if slug_affinity(text, segment):
            score += SLUG_BONUS
        scores[text] = max(scores.get(text, score), score)

    add(og, OG_SCORE)
    add(classed, CLASSED_HEADING_SCORE)
    add(h1, H1_SCORE)
    add(doc, TITLE_TAG_SCORE)
    # When <title> wraps the h1 ("Section : Post" or "Post · Section"),
    # the other piece competes as a candidate: it wins on slug affinity
    # (AoPS's slug matches the remainder, not its blog-name h1) or, with
    # no slug signal, on length.
    if h1 and doc and doc != h1:
        rest = ""
        if doc.startswith(h1):
            rest = doc[len(h1) :].strip(" :-–—|·")
        elif doc.endswith(h1):
            rest = doc[: -len(h1)].strip(" :-–—|·")
        if rest:
            bonus = LONGER_REMAINDER_BONUS if len(rest) > len(h1) else 0.0
            add(rest, TITLE_REMAINDER_SCORE + bonus)

    if not scores:
        return ""
    best = max(scores, key=lambda t: (scores[t], len(t)))
    return best if scores[best] > 0 else ""


def compact(text: str) -> str:
    return re.sub(r"[^a-z0-9]", "", text.lower())


def slug_affinity(text: str, segment: str) -> bool:
    """Whether text plausibly generated the URL slug segment.

    Gated similarity rather than containment, so truncated slugs still
    match ("many-hard-leetcode-problems-are-easy-constraint" vs the full
    title). Below the threshold the signal contributes nothing.
    """
    if not text or not segment:
        return False
    slug = slugify(text)
    if slug in segment:
        return True
    return difflib.SequenceMatcher(None, slug, segment).ratio() >= 0.6


def strip_site_name(title: str, site_name: str) -> str:
    """Drop a leading "Site Name - " or trailing "- Site Name" segment
    exactly matching a known site name (masthead or og:site_name).

    The comma separator (nightingaledvs.com titles pages
    "Post, Nightingale") is safe only here, where the tail must equal a
    declared site name exactly."""
    if not site_name:
        return title
    for separator in [" - ", " | ", " – ", " — ", " · ", ": ", ", "]:
        head, found, tail = title.partition(separator)
        if found and tail and compact(head) == compact(site_name):
            return tail.strip()
        head, found, tail = title.rpartition(separator)
        if found and head and compact(tail) == compact(site_name):
            return head.strip()
    return title


def strip_site_suffix(title: str, domain: str) -> str:
    """Drop a trailing "- Site Name" segment when it matches the domain.

    A match is either containment ("Bloomberg" in bloomberg.com) or the
    tail starting with the domain's label ("Chad Nauseam Home" for
    chadnauseam.com).
    """
    label = compact(domain.split(".")[-2]) if domain.count(".") else ""
    for separator in [" - ", " | ", " – ", " — ", " · "]:
        head, found, tail = title.rpartition(separator)
        if not (found and head and compact(tail)):
            continue
        if compact(tail) in compact(domain) or (
            label and compact(tail).startswith(label)
        ):
            return head.strip()
    return title


def slugify(text: str) -> str:
    # NFKD + ASCII round-trip transliterates accents: Abrégé -> Abrege
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    text = re.sub(r"['’]", "", text.lower())
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", text)).strip("-")


def page_slug(url: str, html: str) -> str:
    domain = urlparse(url).netloc.removeprefix("www.")
    if slug := slugify(page_title(html, domain, url)):
        return slug
    segments = [s for s in urlparse(url).path.split("/") if s]
    return slugify(segments[-1]) if segments else "untitled"


def paywalled(html: str) -> bool:
    """Whether the page is a paywalled stub (Substack's audience marker;
    the quotes appear backslash-escaped inside its preload JSON)."""
    return bool(re.search(r'audience\\?":\\?"only_paid', html))


def normalize(url: str) -> str:
    parsed = urlparse(url)
    base = parsed.netloc.removeprefix("www.") + parsed.path.rstrip("/")
    # Queries are noise (tracking params), except when they carry the
    # page identity, as in youtube.com/watch?v=...
    if match := re.search(r"(?:^|&)v=([^&]+)", parsed.query):
        base += f"?v={match.group(1)}"
    return base
